/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e015b6bd-7969-4521-a50b-28c068e1fffd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dAXtFT3MM",
    "aws_user_pools_web_client_id": "751bao4rvrqosl38cvd56qgl42",
    "oauth": {}
};


export default awsmobile;
